### ISSUE TITLE
New command: /nowplaying

### ISSUE THREAD

**Issue by Daanisaanwezig** [Daanisaanwezig/Discord-Radio#7]
### Feature request
Add a `/nowplaying` command that shows the song that is currently playing, this could be pulled from the status of the bot which is already displaying the song it is playing at that moment.
A command like this can be useful when the bot is not displayed high up in the member list and thus making it more difficult to see the status of the bot.

**Comment by Croustys** [comment]
I'd gladly work on this!

**Comment by Daanisaanwezig** [comment]
> I'd gladly look into working on this!

Sure, I'll assign you to the issue.
If there is anything you need to know feel free to ask.

**Comment by Croustys** [comment]
I'm not sure I'm understanding the codebase correctly, some files have random `export{}` lines in them. Also `import` modules are being used along with `module.exports`, which is quite baffling & inconsistent.

Also I can't seem to find if there's a process anywhere, which stores the song currently being played.

Another line I can't wrap my head around is `let jsfile = files.filter( f => f.split( '.' ).pop() === 'js' )`
What is this line supposed to do? filter out the js files in a typescript enviroment? if so it doesn't work, since it returns an empty list.

Thanks for your time & help in advance!

**Comment by Daanisaanwezig** [comment]
There indeed is a inconsistency in the code right now regarding the import function and require, however the module.exports is being used for the new [Discord slash commands](https://discordjs.guide/interactions/replying-to-slash-commands.html#receiving-interactions).
The export is added to each file because TypeScript complains when you import/require libraries, using `export{}` fixes it. I know this might not be the most elegant solution, but it works. If you have a better solution you are more than welcome to create a new issue and solve it.

The song isn't being stored anywhere, it is however updated in the status of the bot which can be read when getting the bot as a user.

For the last question, this is because TypeScript is being compiled back to JavaScript, so while yes the file is a `.ts` file, when running the bot it will be a `.js` file.

I hope this answers your questions, if not feel free to ask more questions.

**Comment by Croustys** [comment]
submitted a PR #13 
Thanks for your help, I was thinking about another way of displaying the current song other than getting it from that status but as you said it is not being stored globally anywhere, so for the time being it should be a good solution.

Let me know if you have any questions regarding the PR!
